CREATE DATABASE IF NOT EXISTS devdb;

USE devdb;

CREATE TABLE IF NOT EXISTS complaints (
    unique_key VARCHAR(50) PRIMARY KEY,
    created_date DATETIME,
    closed_date DATETIME,
    agency VARCHAR(100),
    agency_name VARCHAR(100),
    complaint_type VARCHAR(255),
    descriptor VARCHAR(255),
    descriptor_2 VARCHAR(255),
    location_type VARCHAR(50),
    incident_zip VARCHAR(10),
    incident_address VARCHAR(255),
    street_name VARCHAR(255),
    cross_street_1 VARCHAR(255),
    cross_street_2 VARCHAR(255),
    intersection_street_1 VARCHAR(255),
    intersection_street_2 VARCHAR(255),
    address_type VARCHAR(50),
    city VARCHAR(100),
    borough VARCHAR(50),
    landmark VARCHAR(255),
    facility_type VARCHAR(255),
    status VARCHAR(50),
    due_date DATETIME,
    resolution_description TEXT,
    resolution_action_updated_date DATETIME,
    community_board VARCHAR(20),
    council_district VARCHAR(20),
    police_precinct VARCHAR(50),
    open_data_channel_type VARCHAR(50),
    park_facility_name VARCHAR(255),
    park_borough VARCHAR(50),
    vehicle_type VARCHAR(50),
    taxi_company_borough VARCHAR(50),
    taxi_pick_up_location VARCHAR(255),
    bridge_highway_name VARCHAR(255),
    bridge_highway_direction VARCHAR(50),
    road_ramp VARCHAR(50),
    bridge_highway_segment VARCHAR(50),
    latitude DOUBLE,
    longitude DOUBLE,
    x_coordinate_state_plane DOUBLE,
    y_coordinate_state_plane DOUBLE,
    bbl VARCHAR(20),
    council_district VARCHAR(20),
    location POINT
);
